webtalk_init -webtalk_dir F:/Academic/PCIe_Dev/TTE_Card/TTE_Test/TTE_Card/TTE_Card.sim/sim_1/behav/xsim/xsim.dir/Clk_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 29 16:15:00 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211714116_0_0_428" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "94c98586-9bde-41e7-97c8-3fb33b606934" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "29865ef3c393471981f133755532dee1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "8" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11644_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3063774934 -regid "211714116_0_0_428" -xml F:/Academic/PCIe_Dev/TTE_Card/TTE_Test/TTE_Card/TTE_Card.sim/sim_1/behav/xsim/xsim.dir/Clk_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/Academic/PCIe_Dev/TTE_Card/TTE_Test/TTE_Card/TTE_Card.sim/sim_1/behav/xsim/xsim.dir/Clk_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/Academic/PCIe_Dev/TTE_Card/TTE_Test/TTE_Card/TTE_Card.sim/sim_1/behav/xsim/xsim.dir/Clk_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
